<div id="hji-spm-idx__<?php echo $context['slug']; ?>-tp" aria-labelledby="<?php echo $context['slug']; ?>" class="hji-spm-idx__tab-panel <?php echo $context['class']; ?>">
    <form id="hji-spm-idx__form-<?php echo $context['slug']; ?>" action="<?php echo home_url('/wp-admin/admin.php?page=hji-spatialmatch-idx&action=save-compliance-settings');?>" method="post">
        <?php wp_nonce_field(); ?>

        <h3>Compliance</h3>

        <div id="info-texas_info" class="redux-info redux-notice-field redux-field-info">
            <p class="redux-info-desc">
                <b>Texas Requirements</b>
                <br>
                The state of Texas requires that all Real Estate brokers and agents display an official "Information About Brokerage Services"
                form as well as the "Texas Real Estate Commission Regulations" document on their website.
            </p>
        </div>

        <div id="info-texas_iabs_info" class="redux-info   redux-info-field redux-field-info">
            <p class="redux-info-desc">
                <b>Need to Complete the IABS form?</b>
                <br>
                <a href="<?php echo \SpatialMatchIdx\front\compliances\compliancesMarkets\TexasCompliance::IABS_FORM; ?>" target="_blank">
                    Grab a copy of the required form here
                </a>.
                Then you can complete it and upload it to your website using the upload button above.
            </p>
        </div>

        <?php
        wp_enqueue_media();
        $existFile = !empty($context['data']['file_src']);
        $compliance_file_icon_dispaly = !empty($context['data']['file_src']) ? 'block' : 'none';
        ?>

        <div>
            <input id="compliance_file_src" type="hidden" name="<?php echo $context['slug']; ?>[file_src]" value="<?php  echo $context['data']['file_src']; ?>" />
            <input id="compliance_file_name" type="hidden" name="<?php echo $context['slug']; ?>[file_name]" value="<?php  echo $context['data']['file_name']; ?>" />
            <div id="compliance_file_icon" style="display: <?php echo $compliance_file_icon_dispaly ?>">
                <a target="blank" href="<?php  echo $context['data']['file_src']; ?>" title="<?php  echo $context['data']['file_name']; ?>">
                    <img class="compliance-option-image" src="/wp-includes/images/media/document.png" alt="">
                </a>
            </div>
            <button type="submit" class="upload_compliance_button button" style="display: <?php echo !$existFile ? 'block' : 'none'; ?>">Upload</button>
            <button type="submit" class="remove_compliance_button button" style="display: <?php echo $existFile ? 'block' : 'none'; ?>">&times;</button>
            <div>Add your completed IABS form here.</div>
        </div>

        <button type="submit" class="button button-primary">Save Changes</button>
    </form>
</div>
