<div class="hji-spatialmatch-idx__help-page hji-spatialmatch-idx__page wrap">
    <header class="hji-spm-idx__header">
        <div class="hji-spm-idx__page-title">
            <h1>Help - SpatialMatch IDX</h1>
        </div>
        <a href="#">
            <img src="<?php echo SPATIALMATCH_IDX_URL; ?>assets/img/logo.png" height="60px" alt="">
        </a>
    </header>
    <div class="container">
        <main class="hji-spm-idx__main">
            <section class="hji-spm-idx__top-section">
                <h2 class="header-section">Help</h2>
                <div class="hji-spm-idx__top-section-wrapper">
                    <ul class="hji-spm-idx__list">
                        <li class="hji-spm-idx__list-item">
                            <a class="hji-spm-idx__link" href="https://docs.homejunction.com/article/400-spatialmatch-template-hooks" target="_blank">
                                How to change IDX page meta title & meta description?
                            </a>
                        </li>
                        <li class="hji-spm-idx__list-item">
                            <a class="hji-spm-idx__link" href="https://docs.homejunction.com/article/400-spatialmatch-template-hooks" target="_blank">
                                How to customize IDX page template?
                            </a>
                        </li>
                        <li class="hji-spm-idx__list-item">
                            <a class="hji-spm-idx__link" href="https://docs.homejunction.com/article/400-spatialmatch-template-hooks" target="_blank">
                                How to setup Google Analytics with SpatialMatch IDX?
                            </a>
                        </li>
                        <li class="hji-spm-idx__list-item">
                            <a class="hji-spm-idx__link" href="https://docs.homejunction.com/article/212-zapier-integration#inquiries" target="_blank">
                                How to send leads to my CRM?
                            </a>
                        </li>
                    </ul>

                    <div class="hji-spm-idx__info-box">
                        <div class="row">
                            <div class="hji-spm-idx__row-title">Home Junction</div>
                            <div>
                                <a href="https://homejunction.com" target="_blank">
                                    www.homejunction.com
                                </a>
                            </div>
                        </div>
                        <div class="row">
                            <div class="hji-spm-idx__row-title">Customer Support</div>
                            <div class="flex-column">
                                <a href="mailto:help@homejunction.com" >
                                    help@homejunction.com
                                </a><br>
                                <a href="tel:(858) 777 - 9533">(858) 777 - 9533 x4</a>
                            </div>
                        </div>
                        <div class="row">
                            <div class="hji-spm-idx__row-title">
                                Sales Department
                            </div>
                            <div class="flex-column">
                                <a href="tel:(858) 777 - 9533">(858) 777 - 9533 x3</a></div>
                        </div>
                    </div>
                </div>

            </section>
            <section class="hji-spm-idx__content-section">
                <h2>
                    About Home Junction, Inc.
                </h2>
                <p>
                    Based in San Diego, CA, Home Junction is a data technology company that specializes in real estate data and boundary licensing, custom websites created with WordPress real estate themes, WordPress real estate plugins and additional services. The company provides an extensive number of data layers on home sales, neighborhoods, schools, school attendance zones, demographics, home value estimates, geospatial boundaries, and other information.
                </p>
                <p>
                    In summer of 2020 Home Junction became part of <a href="https://www.attomdata.com/" target="_blank">ATTOM Data Solutions</a> - the nation's premier provider of real estate and property data.
                </p>
                <p>
                    For information on our WordPress line of products, like the ones listed below, contact our sales department at (858) 777 - 9533 x3 or email <a href="mailto:help@homejunction.com">help@homejunction.com</a>.
                </p>
            </section>
        </main>
    </div>

    <div class="hji-spm-idx__license--section">
        <div class="hji-spm-idx__license--wrap">
            <div class="hji-spm-idx__license--card">
                <div class="hji-spm-idx__license--card--header"><img src="<?php echo SPATIALMATCH_IDX_URL; ?>assets/img/logo-white.png" alt="Logo"></div>
                <div class="hji-spm-idx__license--card--title">Responsive IDX</div>
                <div class="hji-spm-idx__license--card--body">SEO Friendly Indexable IDX Listings</div>
            </div>
        </div>
        <div class="hji-spm-idx__license--wrap">
            <div class="hji-spm-idx__license--card">
                <div class="hji-spm-idx__license--card--header"><img src="<?php echo SPATIALMATCH_IDX_URL; ?>assets/img/logo-white.png" alt="Logo"></div>
                <div class="hji-spm-idx__license--card--title">Agent Roster</div>
                <div class="hji-spm-idx__license--card--body">Agents, Teams, Brokerages, Listings, Past Sales and more</div>
            </div>
        </div>
        <div class="hji-spm-idx__license--wrap">
            <div class="hji-spm-idx__license--card">
                <div class="hji-spm-idx__license--card--header"><img src="<?php echo SPATIALMATCH_IDX_URL; ?>assets/img/logo-white.png" alt="Logo"></div>
                <div class="hji-spm-idx__license--card--title">Pocket Listings</div>
                <div class="hji-spm-idx__license--card--body">Manage Non-MLS Listings SEO Friendly</div>
            </div>
        </div>
        <div class="hji-spm-idx__license--wrap">
            <div class="hji-spm-idx__license--card">
                <div class="hji-spm-idx__license--card--header"><img src="<?php echo SPATIALMATCH_IDX_URL; ?>assets/img/logo-white.png" alt="Logo"></div>
                <div class="hji-spm-idx__license--card--title">Recent Sales</div>
                <div class="hji-spm-idx__license--card--body">Display Historic Sales Data in any Area</div>
            </div>
        </div>
        <div class="hji-spm-idx__license--wrap">
            <div class="hji-spm-idx__license--card">
                <div class="hji-spm-idx__license--card--header"><img src="<?php echo SPATIALMATCH_IDX_URL; ?>assets/img/logo-white.png" alt="Logo"></div>
                <div class="hji-spm-idx__license--card--title">Home Value</div>
                <div class="hji-spm-idx__license--card--body">Generate Seller Leads via Automated Home Valuation</div>
            </div>
        </div>
        <div class="hji-spm-idx__license--wrap">
            <div class="hji-spm-idx__license--card">
                <div class="hji-spm-idx__license--card--header"><img src="<?php echo SPATIALMATCH_IDX_URL; ?>assets/img/logo-white.png" alt="Logo"></div>
                <div class="hji-spm-idx__license--card--title">Schools</div>
                <div class="hji-spm-idx__license--card--body">Schools, Demographics, Districts & Attendance Areas</div>
            </div>
        </div>
        <div class="hji-spm-idx__license--wrap">
            <div class="hji-spm-idx__license--card">
                <div class="hji-spm-idx__license--card--header"><img src="<?php echo SPATIALMATCH_IDX_URL; ?>assets/img/logo-white.png" alt="Logo"></div>
                <div class="hji-spm-idx__license--card--title">Geo Farms</div>
                <div class="hji-spm-idx__license--card--body">Interactive and data-rich Neighborhood Pages</div>
            </div>
        </div>
    </div>
</div>

