<div class="hji-spatialmatch-idx__license-registration-page hji-spatialmatch-idx__page wrap">
    <header class="hji-spm-idx__header">
        <div class="hji-spm-idx__page-title">
            <h1>Settings - SpatialMatch IDX</h1>
        </div>
        <a href="#">
            <img src="<?php echo SPATIALMATCH_IDX_URL; ?>assets/img/logo.png" height="60px" alt="">
        </a>
    </header>
    <div class="container">
        <main class="hji-spm-idx__main">
            <h2>Select License Type</h2>
            <section class="hji-spm-idx__top-section wrap">
                <div class="hji-spm-idx__license--section">
                    <div class="hji-spm-idx__license--wrap">
                        <div class="hji-spm-idx__license--card">
                            <div class="hji-spm-idx__license--card--header">Limited Trial</div>
                            <div class="hji-spm-idx__license--card--title">10 Day Free Trial</div>
                            <div class="hji-spm-idx__license--card--body">We like to try things.<br> Do you?</div>
                        </div>
                        <a class="button button-secondary" href="<?php site_url();?>/wp-admin/admin.php?page=hji-spatialmatch-idx&action=trial-license-registration">Get Trial License</a>
                    </div>

                    <div class="hji-spm-idx__license--wrap">
                        <div class="hji-spm-idx__license--card hji-spm-idx__license--card--xl">
                            <div class="hji-spm-idx__license--card--header">Paid Subscription</div>
                            <div class="hji-spm-idx__license--card--title">$99.95/mo</div>
                            <div class="hji-spm-idx__license--card--body">Going live in 1..2..</div>
                        </div>
                        <a class="button button-primary" href="<?php site_url();?>/wp-admin/admin.php?page=hji-spatialmatch-idx&action=agent-license-registration">Get Agent/Broker License</a>
                    </div>

                    <div class="hji-spm-idx__license--wrap">
                        <div class="hji-spm-idx__license--card">
                            <div class="hji-spm-idx__license--card--header">Developer License</div>
                            <div class="hji-spm-idx__license--card--title">$0</div>
                            <div class="hji-spm-idx__license--card--body">Not an agent?<br> Need time for integration?</div>
                        </div>
                        <a class="button button-secondary" href="<?php site_url();?>/wp-admin/admin.php?page=hji-spatialmatch-idx&action=developer-license-registration">Get Developer License</a>
                    </div>
                </div>
            </section>
        </main>
    </div>
</div>
