<div class="hji-spatialmatch-idx__license-registration-page hji-spatialmatch-idx__page">
    <header class="hji-spm-idx__header">
        <div class="hji-spm-idx__page-title">
            <h1></h1>
        </div>
        <a href="#">
            <img src="<?php echo SPATIALMATCH_IDX_URL; ?>assets/img/logo.png" height="60px" alt="">
        </a>
    </header>
    <div class="container">
        <main class="hji-spm-idx__main">
            <h1>Your license key is on its way! Check your email.</h1>
            <p>
                To complete configuration, simply paste your license key into the SpatialMatch IDX settings.
            </p>
            <p>
                To learn more about SpatialMatch IDX click <a href="<?php site_url();?>/wp-admin/admin.php?page=hji-spatialmatch-idx-help">here</a> or contact our <a href="/wp-admin/admin.php?page=hji-spatialmatch-idx-help">support</a>.
            </p>
            <p>
                Thank you!
            </p>
        </main>
    </div>
</div>
