<!DOCTYPE html>
<html lang="en-US" style="height: 100%">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>NWMLS DMCA Notice</title>
    <?php wp_site_icon(); ?>
</head>
<body>
<div class="site-wrapper" data-init="site-wrapper">
    <div class="content" style="max-width: 1200px; margin-left: auto; margin-right: auto">
        <h1>NWMLS DMCA Notice</h1>
        <h2>Claims of Copyright Infringement &amp; Related Issues (17 USC § 512 et seq.).</h2>
        <div>&nbsp;</div>
        <p>We respect the intellectual property rights of others. Anyone who believes their work has been reproduced in a way that constitutes copyright infringement may notify our agent by providing the following information:</p>
        <ol type="a">
            <li>
                <p>Identification of the copyrighted work that you claim has been infringed, or, if multiple copyrighted works at a single online site are covered by a single notification, a representative list of such works at the site;</p>
            </li><li>
                <p>Identification of the material that you claim is infringing and needs to be removed, including a description of where it is located so that the copyright agent can locate it;</p>
            </li><li>
                <p>Your address, telephone number, and, if available, e-mail address, so that the copyright agent may contact you about your complaint; and</p>
            </li><li>
                <p>A signed statement that the above information is accurate; that you have a good faith belief that the identified use of the material is not authorized by the copyright owner, its agent, or the law; and, under penalty of perjury, that you are the copyright
                    owner or are authorized to act on the copyright owner's behalf in this situation.</p>
            </li></ol>
        <p>Upon obtaining such knowledge we will act expeditiously to remove, or disable access to, the material. Please be aware that there are substantial penalties for false claims.
        </p>
        <div>&nbsp;</div>
        <p>If a notice of copyright infringement has been wrongly filed against you, you may submit a counter notification to our agent. A valid counter notification is a written communication that incorporates the following elements:</p>
        <ol type="a">
            <li>
                <p>A physical or electronic signature of the poster;</p>
            </li><li>
                <p>Identification of the material that has been removed or to which access has been disabled and the location at which the material appeared before it was removed or access to it was disabled;</p>
            </li><li>
                <p>A statement under penalty of perjury that you have a good faith belief that the material was removed or disabled as a result of mistake or misidentification;</p>
            </li><li>
                <p>Your name, address, and telephone number; a statement that you consent to the jurisdiction of federal district court for the judicial district in which your address is located, or if your address is outside of the U.S., for any judicial district in which
                    the service provider may be found; and that you will accept service of process from the complainant.</p>
            </li></ol>
        <div>&nbsp;</div>
        <p>Notices of the foregoing copyright issues should be sent as follows:</p>
        <p><strong>By mail:</strong><br>
            <?php  echo $context['officeName']; ?><br>
            <?php  echo $context['address']['deliveryLine']; ?><br>
            <?php  echo $context['address']['city']; ?>, <?php  echo $context['address']['state']; ?> <?php  echo $context['address']['zip']; ?><br>
            United States<br>
            Attention: <?php  echo $context['name']; ?><br>
        </p>
        <p><strong>By e-mail:</strong><br>
            <a href="mailto:<?php  echo $context['email']; ?>"><?php  echo $context['email']; ?></a>
        </p>
        <p>If you give notice of copyright infringement by e-mail, an agent may begin investigating the alleged copyright infringement; however, we must receive your signed statement by mail or as an attachment to your e-mail before we are required to take any action.
        </p>
        <p>This information should not be construed as legal advice. We recommend you seek independent legal counsel before filing a notification or counter-notification. For further information about the DMCA, please visit the website of the United States Copyright
            Office at: <a href="redir.aspx?C=36565282c2404594b6f7df67623ab9b5&amp;URL=http%3a%2f%2fwww.copyright.gov%2fonlinesp" target="_blank">
                http://www.copyright.gov/onlinesp</a>.</p>
    </div>
</div>
</body>
</html>
